version: "3"

services:
  server:
    image: nginx
    ports:
      - 80:80
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./static:/usr/share/nginx/html/static
    depends_on:
      - web
      - registry

  registry:
    build: registry
    environment:
      - PROXY_ADDRESS=${PROXY_ADDRESS}
      - PROXY_PORT=${PROXY_PORT}

  web:
    build: web
    environment:
      - DB_HOST=db
      - DB_DATABASE=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
